import type { CandidateItem } from '../types/session';

export interface CategoryPreset {
  id: string;
  name: string;
  icon: string;
  sampleQuery: string;
  category: string;
  budgetCeiling: number;
  currency: string;
  candidates: CandidateItem[];
}

export const COMMERCE_CATALOG: Record<string, CandidateItem[]> = {
  HOTEL: [
    {
      id: 'HOTEL-GOA-01',
      name: 'Goa Grand Heritage Resort & Spa',
      merchant: 'Goa Hospitality Group',
      merchantId: 'MER-GOAHOSP',
      category: 'HOTEL',
      price: 2460,
      currency: 'INR',
      location: 'Calangute, North Goa',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      rating: 4.8,
      reviewsCount: 1420,
      availability: 'In Stock - 3 Rooms Left',
      delivery: 'Instant Keyless Digital Check-in',
      description: '5-star rated beachside heritage property 200m from Calangute beach with lush tropical gardens, outdoor lagoon pool, and complimentary gourmet breakfast buffet.',
      selectionScore: 96,
      selectionProbability: '96%',
      rank: 1,
      isYou: true,
      isAiSelected: true,
      attributes: {
        'Room Category': 'Deluxe AC Suite with Ocean Balcony',
        'Beach Proximity': '200m to Calangute Beach',
        'Breakfast': 'Complimentary Gourmet Buffet Included',
        'Key Amenities': 'High-Speed WiFi, Lagoon Pool, Spa',
        'Check-in / Policy': '24/7 Digital Check-in, Free Cancellation',
      },
      aiFactors: {
        intentMatch: 98,
        budgetFit: 96,
        productQuality: 97,
        merchantTrust: 99,
        availabilityScore: 94,
        fulfillmentScore: 98,
        catalogCompleteness: 99,
        aiDiscoverability: 98,
        decisionFactors: [
          'Highest weighted multi-factor score (96%) balancing luxury rating with budget buffer',
          'Aegis Verified Whitelist Merchant with 99.8% dispute-free fulfillment history',
          'Price ₹2,460 fits strictly within ₹3,000 ceiling with an 18% cost buffer',
          'Complimentary breakfast inclusion saves an estimated ₹450/day per guest',
        ],
      },
    },
    {
      id: 'HOTEL-GOA-02',
      name: 'Calangute Palm Cove Suites',
      merchant: 'Coastal Getaways Ltd',
      merchantId: 'MER-COASTAL',
      category: 'HOTEL',
      price: 2850,
      currency: 'INR',
      location: 'Calangute Main Road, Goa',
      image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80',
      rating: 4.6,
      reviewsCount: 890,
      availability: 'Available - 5 Rooms',
      delivery: 'Instant Confirmation',
      description: 'Modern boutique suites situated close to prime dining strip with rooftop plunge pool and stylish minimalist design.',
      selectionScore: 91,
      selectionProbability: '91%',
      rank: 2,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Room Category': 'Executive King Room',
        'Beach Proximity': '650m to Beach',
        'Breakfast': 'Available on Request (₹250)',
        'Key Amenities': 'Rooftop Plunge Pool, AC, WiFi',
        'Check-in / Policy': 'Standard 12:00 PM Check-in',
      },
      aiFactors: {
        intentMatch: 92,
        budgetFit: 88,
        productQuality: 91,
        merchantTrust: 94,
        availabilityScore: 95,
        fulfillmentScore: 92,
        catalogCompleteness: 92,
        aiDiscoverability: 90,
        decisionFactors: [
          'Strong guest rating (4.6 / 5.0) but narrower budget buffer (₹2,850 vs ₹3,000 ceiling)',
          'Breakfast not included by default, reducing overall commerce utility',
          'Slightly further from beachfront (650m) compared to Rank #1',
        ],
      },
    },
    {
      id: 'HOTEL-GOA-03',
      name: 'Baga Azure Boutique Retreat',
      merchant: 'Azure Hospitality Group',
      merchantId: 'MER-AZURE',
      category: 'HOTEL',
      price: 2200,
      currency: 'INR',
      location: 'Baga Creek Rd, Goa',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
      rating: 4.4,
      reviewsCount: 620,
      availability: 'Available - 2 Rooms Left',
      delivery: 'Instant Confirmation',
      description: 'Tranquil retreat nestled near Baga creek with bohemian decor, lush garden patio, and artisanal cafe.',
      selectionScore: 88,
      selectionProbability: '88%',
      rank: 3,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Room Category': 'Deluxe Garden Cottage',
        'Beach Proximity': '900m to Baga Beach',
        'Breakfast': 'Continental Included',
        'Key Amenities': 'Garden Cafe, High-Speed WiFi, AC',
        'Check-in / Policy': 'Digital Keypad Access',
      },
      aiFactors: {
        intentMatch: 87,
        budgetFit: 94,
        productQuality: 86,
        merchantTrust: 90,
        availabilityScore: 82,
        fulfillmentScore: 89,
        catalogCompleteness: 88,
        aiDiscoverability: 86,
        decisionFactors: [
          'Great price point of ₹2,200 providing 26% budget safety buffer',
          'Slightly lower customer sentiment on room acoustics and pool absence',
          'Limited availability (2 rooms) introduces allocation risk',
        ],
      },
    },
    {
      id: 'HOTEL-GOA-04',
      name: 'Anjuna Sun & Sand Villa',
      merchant: 'SunStay Vacation Homes',
      merchantId: 'MER-SUNSTAY',
      category: 'HOTEL',
      price: 2990,
      currency: 'INR',
      location: 'Anjuna Flea Market Rd, Goa',
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
      rating: 4.5,
      reviewsCount: 410,
      availability: '1 Villa Unit Left',
      delivery: 'Host Confirmation (1-2 Hours)',
      description: 'Private Portuguese heritage villa near the famous Anjuna cliffside with secluded courtyard and kitchen.',
      selectionScore: 84,
      selectionProbability: '84%',
      rank: 4,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Room Category': 'Private Villa Room with Patio',
        'Beach Proximity': '1.2 km to Anjuna Beach',
        'Breakfast': 'Self-Catering Kitchen Available',
        'Key Amenities': 'Full Kitchenette, Private Patio, AC',
        'Check-in / Policy': 'Host Met Check-in',
      },
      aiFactors: {
        intentMatch: 85,
        budgetFit: 78,
        productQuality: 90,
        merchantTrust: 86,
        availabilityScore: 70,
        fulfillmentScore: 80,
        catalogCompleteness: 85,
        aiDiscoverability: 84,
        decisionFactors: [
          'Near-ceiling price (₹2,990 vs ₹3,000) leaves negligible variance margin',
          'Non-instant confirmation requires 1-2 hour host approval window',
          'Distance to beach (1.2 km) scores lower on location proximity invariant',
        ],
      },
    },
    {
      id: 'HOTEL-GOA-05',
      name: 'Panaji Riverfront Express Inn',
      merchant: 'BudgetStay Express Network',
      merchantId: 'MER-BUDGETSTAY',
      category: 'HOTEL',
      price: 1850,
      currency: 'INR',
      location: 'Panaji Commercial Center, Goa',
      image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
      rating: 4.0,
      reviewsCount: 210,
      availability: 'Available - 8 Rooms',
      delivery: 'Instant Confirmation',
      description: 'Economical, clean business traveler lodge situated in Panaji commercial district. Functional amenities at low cost.',
      selectionScore: 79,
      selectionProbability: '79%',
      rank: 5,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Room Category': 'Standard Double Room',
        'Beach Proximity': '16 km to Calangute/Baga',
        'Breakfast': 'Not Included (₹150 addon)',
        'Key Amenities': 'AC, Work Desk, Standard WiFi',
        'Check-in / Policy': '24-hour Front Desk',
      },
      aiFactors: {
        intentMatch: 68,
        budgetFit: 99,
        productQuality: 72,
        merchantTrust: 82,
        availabilityScore: 98,
        fulfillmentScore: 90,
        catalogCompleteness: 75,
        aiDiscoverability: 74,
        decisionFactors: [
          'Lowest absolute price (₹1,850), demonstrating AI does NOT simply pick the cheapest candidate',
          'Severe location penalty: 16 km away from beach leisure zone violates user intent context',
          'Customer satisfaction rating (4.0 / 5.0) fails top-tier quality threshold',
        ],
      },
    },
    {
      id: 'HOTEL-GOA-06',
      name: 'Vagator Cliffside Haven',
      merchant: 'Cliffside Hospitality',
      merchantId: 'MER-CLIFF',
      category: 'HOTEL',
      price: 2700,
      currency: 'INR',
      location: 'Vagator Beach Road, Goa',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80',
      rating: 4.2,
      reviewsCount: 340,
      availability: 'Available - 4 Rooms',
      delivery: 'Instant Confirmation',
      description: 'Rustic clifftop chalets overlooking Arabian sea sunsets with open-air lounge and cafe.',
      selectionScore: 76,
      selectionProbability: '76%',
      rank: 6,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Room Category': 'Standard Sea-Facing Chalet',
        'Beach Proximity': '400m steep path to Vagator',
        'Breakfast': 'Paid Add-on',
        'Key Amenities': 'Sunset Deck, WiFi, Fan/AC',
        'Check-in / Policy': 'Standard Front Desk',
      },
      aiFactors: {
        intentMatch: 78,
        budgetFit: 84,
        productQuality: 75,
        merchantTrust: 80,
        availabilityScore: 85,
        fulfillmentScore: 82,
        catalogCompleteness: 78,
        aiDiscoverability: 75,
        decisionFactors: [
          'Steep cliff access noted in customer reviews as difficult for transit',
          'Occasional WiFi connectivity dips in clifftop zone degrade digital nomad utility',
          'Weighted selection score falls below category median',
        ],
      },
    },
  ],

  LAPTOP: [
    {
      id: 'LAP-01',
      name: 'ZenBook Pro 14 OLED AI Ultra',
      merchant: 'TechHub Direct',
      merchantId: 'MER-TECHHUB',
      category: 'LAPTOP',
      price: 56990,
      currency: 'INR',
      location: 'Bangalore Tech Park Hub',
      image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
      rating: 4.8,
      reviewsCount: 960,
      availability: 'In Stock - Ships Today',
      delivery: 'Free Next-Day Air Delivery',
      description: 'Ultraportable AI powerhouse featuring 14" 2.8K 120Hz OLED, Intel Core Ultra 5 with dedicated Neural Processing Unit (NPU), 16GB LPDDR5X RAM, and 512GB Gen4 NVMe.',
      selectionScore: 97,
      selectionProbability: '97%',
      rank: 1,
      isYou: true,
      isAiSelected: true,
      attributes: {
        'Processor': 'Intel Core Ultra 5 125H (14-Core / Dedicated NPU)',
        'Memory / RAM': '16GB LPDDR5X 7467MHz Dual Channel',
        'Storage': '512GB PCIe 4.0 NVMe SSD (Up to 5000MB/s)',
        'Display': '14" 2.8K (2880x1800) 120Hz 0.2ms OLED 100% DCI-P3',
        'Battery Life': '75Wh (Up to 16 Hours Tested)',
        'Chassis': '1.28 kg Magnesium-Aluminum Military STD-810H',
      },
      aiFactors: {
        intentMatch: 99,
        budgetFit: 95,
        productQuality: 98,
        merchantTrust: 99,
        availabilityScore: 98,
        fulfillmentScore: 99,
        catalogCompleteness: 99,
        aiDiscoverability: 98,
        decisionFactors: [
          'Dedicated NPU hardware enables local on-device AI acceleration',
          'Class-leading 2.8K OLED display outshines all competitor IPS panels',
          'Complies with sub-₹60,000 budget with ₹3,010 safe overhead (₹56,990)',
          'Top-tier merchant trust with 99.4% next-day fulfillment track record',
        ],
      },
    },
    {
      id: 'LAP-02',
      name: 'ThinkPad T14s Pro Enterprise Edition',
      merchant: 'Enterprise Computing Store',
      merchantId: 'MER-ENTCOMP',
      category: 'LAPTOP',
      price: 58500,
      currency: 'INR',
      location: 'National Electronics Depot',
      image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&q=80',
      rating: 4.7,
      reviewsCount: 840,
      availability: 'Available - 12 Units',
      delivery: '2-Day Express Delivery',
      description: 'Legendary business workhorse with AMD Ryzen 7 7730U 8-core CPU, spill-resistant keyboard, 16GB DDR4, and dTPM 2.0 hardware security.',
      selectionScore: 92,
      selectionProbability: '92%',
      rank: 2,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'AMD Ryzen 7 7730U (8-Core / 16-Thread)',
        'Memory / RAM': '16GB DDR4 3200MHz',
        'Storage': '512GB PCIe 4.0 SSD',
        'Display': '14" WUXGA (1920x1200) IPS Anti-Glare 400 nits',
        'Battery Life': '57Wh Rapid Charge (80% in 60 mins)',
        'Chassis': 'Carbon Fiber Hybrid, 1.35 kg',
      },
      aiFactors: {
        intentMatch: 93,
        budgetFit: 90,
        productQuality: 94,
        merchantTrust: 96,
        availabilityScore: 92,
        fulfillmentScore: 91,
        catalogCompleteness: 95,
        aiDiscoverability: 91,
        decisionFactors: [
          'Exceptional enterprise keyboard and rugged durability',
          'Standard IPS screen lacks the contrast and 120Hz refresh rate of Rank #1',
          'Higher price point leaves only ₹1,500 budget cushion',
        ],
      },
    },
    {
      id: 'LAP-03',
      name: 'HP Pavilion Aero 13 Magnesium',
      merchant: 'OmniTech Retail',
      merchantId: 'MER-OMNITECH',
      category: 'LAPTOP',
      price: 53990,
      currency: 'INR',
      location: 'Mumbai Tech Hub',
      image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
      rating: 4.5,
      reviewsCount: 620,
      availability: 'In Stock - 8 Units',
      delivery: '3-Day Standard Delivery',
      description: 'Ultra-featherweight 970g notebook with AMD Ryzen 5, bright 16:10 display, and all-day battery life.',
      selectionScore: 89,
      selectionProbability: '89%',
      rank: 3,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'AMD Ryzen 5 7535U (6-Core)',
        'Memory / RAM': '16GB LPDDR5',
        'Storage': '512GB SSD',
        'Display': '13.3" WQXGA (2560x1600) IPS 400 nits',
        'Battery Life': '43Wh (Up to 11 Hours)',
        'Chassis': 'Magnesium-Aluminum 970g',
      },
      aiFactors: {
        intentMatch: 90,
        budgetFit: 96,
        productQuality: 88,
        merchantTrust: 92,
        availabilityScore: 90,
        fulfillmentScore: 88,
        catalogCompleteness: 90,
        aiDiscoverability: 89,
        decisionFactors: [
          'Superb ultralight weight under 1kg is optimal for frequent transit',
          'Smaller 43Wh battery provides less endurance under heavy workloads',
          '6-core CPU trails 14-core Intel Ultra in multithreaded AI tasks',
        ],
      },
    },
    {
      id: 'LAP-04',
      name: 'MacBook Air M2 13" (Certified Refurbished)',
      merchant: 'iStore Certified Outlets',
      merchantId: 'MER-ISTORE',
      category: 'LAPTOP',
      price: 59990,
      currency: 'INR',
      location: 'Certified Apple Partner Depot',
      image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&q=80',
      rating: 4.6,
      reviewsCount: 1150,
      availability: '2 Units Left in Stock',
      delivery: 'Next-Day Delivery',
      description: 'Apple M2 silicon chip with 8-core CPU, Liquid Retina display, MagSafe 3 charging, and silent fanless architecture.',
      selectionScore: 86,
      selectionProbability: '86%',
      rank: 4,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'Apple M2 Silicon (8-Core CPU / 8-Core GPU)',
        'Memory / RAM': '8GB Unified Memory',
        'Storage': '256GB SSD',
        'Display': '13.6" Liquid Retina 500 nits True Tone',
        'Battery Life': '52.6Wh (Up to 18 Hours)',
        'Chassis': '1.24 kg 100% Recycled Aluminum',
      },
      aiFactors: {
        intentMatch: 88,
        budgetFit: 75,
        productQuality: 96,
        merchantTrust: 94,
        availabilityScore: 78,
        fulfillmentScore: 92,
        catalogCompleteness: 88,
        aiDiscoverability: 85,
        decisionFactors: [
          'Priced at ₹59,990 right on the ₹60,000 ceiling margin (only ₹10 buffer)',
          '8GB Unified memory constraint compared to 16GB standard in Windows peers',
          '256GB storage limitation requires external drive for heavy assets',
        ],
      },
    },
    {
      id: 'LAP-05',
      name: 'Acer Aspire 5 Slim Core i5',
      merchant: 'BudgetLaptops Outlet',
      merchantId: 'MER-BUDGETPC',
      category: 'LAPTOP',
      price: 41990,
      currency: 'INR',
      location: 'Central Distribution Center',
      image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&q=80',
      rating: 4.1,
      reviewsCount: 380,
      availability: 'In Stock - 20+ Units',
      delivery: '2-Day Delivery',
      description: 'Budget-friendly 15.6" notebook with 13th Gen Intel Core i5, expandable RAM slots, and numeric keypad.',
      selectionScore: 80,
      selectionProbability: '80%',
      rank: 5,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'Intel Core i5-1335U (10-Core)',
        'Memory / RAM': '16GB DDR4 (Expandable)',
        'Storage': '512GB PCIe SSD',
        'Display': '15.6" FHD (1920x1080) TN 60Hz 250 nits',
        'Battery Life': '50Wh (Up to 7 Hours)',
        'Chassis': '1.78 kg Plastic & Aluminum Lid',
      },
      aiFactors: {
        intentMatch: 76,
        budgetFit: 99,
        productQuality: 74,
        merchantTrust: 86,
        availabilityScore: 96,
        fulfillmentScore: 88,
        catalogCompleteness: 80,
        aiDiscoverability: 78,
        decisionFactors: [
          'Lowest price candidate (₹41,990), confirming AI evaluates overall quality over purely lowest cost',
          'Heavier plastic chassis (1.78kg) and dim 250-nit TN panel lower usability scores',
          'Significantly shorter battery endurance (7h) compared to top candidates',
        ],
      },
    },
    {
      id: 'LAP-06',
      name: 'Lenovo IdeaPad Slim 5 16"',
      merchant: 'PC Galaxy Store',
      merchantId: 'MER-PCGAL',
      category: 'LAPTOP',
      price: 54490,
      currency: 'INR',
      location: 'Regional Hardware Warehouse',
      image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&q=80',
      rating: 4.3,
      reviewsCount: 490,
      availability: 'In Stock - 6 Units',
      delivery: '3-Day Delivery',
      description: 'Spacious 16" productivity laptop with AMD Ryzen 5 7530U, Dolby Audio speakers, and full metal top cover.',
      selectionScore: 77,
      selectionProbability: '77%',
      rank: 6,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'AMD Ryzen 5 7530U (6-Core / 12-Thread)',
        'Memory / RAM': '16GB DDR4 3200MHz',
        'Storage': '512GB SSD',
        'Display': '16" WUXGA (1920x1200) IPS 300 nits',
        'Battery Life': '56.6Wh Rapid Charge Boost',
        'Chassis': '1.89 kg Anodized Aluminum',
      },
      aiFactors: {
        intentMatch: 80,
        budgetFit: 92,
        productQuality: 79,
        merchantTrust: 84,
        availabilityScore: 88,
        fulfillmentScore: 84,
        catalogCompleteness: 82,
        aiDiscoverability: 80,
        decisionFactors: [
          '16-inch form factor is bulkier (1.89kg) for portability constraints',
          'Older DDR4 memory architecture trails LPDDR5X speed benchmark',
          'Overall efficiency rating ranks 6th in comparative AI evaluation',
        ],
      },
    },
  ],

  'RUNNING SHOES': [
    {
      id: 'SHOE-01',
      name: 'Aegis Velocity Carbon Nitro',
      merchant: 'SportyNation Athletic',
      merchantId: 'MER-SPORTYX',
      category: 'RUNNING SHOES',
      price: 4299,
      currency: 'INR',
      location: 'Athletic Performance Hub',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
      rating: 4.9,
      reviewsCount: 2100,
      availability: 'In Stock (All Sizes UK 7-11)',
      delivery: 'Express 2-Day Air Delivery',
      description: 'Elite road tempo racer featuring full-length carbon composite plate, supercritical nitrogen-infused dual foam, and breathable engineered jacquard mesh.',
      selectionScore: 98,
      selectionProbability: '98%',
      rank: 1,
      isYou: true,
      isAiSelected: true,
      attributes: {
        'Midsole Technology': 'Supercritical Nitrogen Dual Foam + Full Carbon Plate',
        'Weight': '205g (Men\'s UK 8) Ultralight Race Spec',
        'Heel-to-Toe Drop': '8mm Dynamic Propulsion Drop',
        'Outsole': 'GripPro High-Traction Wet-Grip Rubber',
        'Upper Material': 'Seamless Engineered Jacquard Weave',
      },
      aiFactors: {
        intentMatch: 99,
        budgetFit: 97,
        productQuality: 99,
        merchantTrust: 99,
        availabilityScore: 98,
        fulfillmentScore: 99,
        catalogCompleteness: 99,
        aiDiscoverability: 99,
        decisionFactors: [
          'Only shoe in sub-₹5,000 bracket with genuine carbon-plate propulsion technology',
          'Exceptional 4.9 / 5.0 rating verified across 2,100+ active road and marathon runners',
          'Optimal cost-benefit balance: ₹4,299 vs ₹5,000 ceiling leaves ₹701 safety margin',
          'Merchant trust score 99/100 with guaranteed hassle-free size replacement warranty',
        ],
      },
    },
    {
      id: 'SHOE-02',
      name: 'Nike Pegasus Air Zoom 40',
      merchant: 'Nike Athletic Direct',
      merchantId: 'MER-NIKEDIR',
      category: 'RUNNING SHOES',
      price: 4895,
      currency: 'INR',
      location: 'Brand Flagship Distribution',
      image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80',
      rating: 4.7,
      reviewsCount: 1850,
      availability: 'In Stock - Popular Sizes',
      delivery: '3-Day Standard Delivery',
      description: 'Iconic daily trainer with responsive React foam and dual Zoom Air cushioning units located in forefoot and heel.',
      selectionScore: 93,
      selectionProbability: '93%',
      rank: 2,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Midsole Technology': 'Nike React Foam + Dual Zoom Air Units',
        'Weight': '285g Balanced Everyday Spec',
        'Heel-to-Toe Drop': '10mm Comfort Training Drop',
        'Outsole': 'Waffle-Inspired Durable Rubber',
        'Upper Material': 'Engineered Single-Layer Mesh',
      },
      aiFactors: {
        intentMatch: 95,
        budgetFit: 88,
        productQuality: 95,
        merchantTrust: 98,
        availabilityScore: 92,
        fulfillmentScore: 92,
        catalogCompleteness: 94,
        aiDiscoverability: 95,
        decisionFactors: [
          'Legendary reliability for high-mileage training',
          'Heavier weight (285g) compared to carbon race-spec (205g)',
          'Higher price point leaves only ₹105 budget buffer',
        ],
      },
    },
    {
      id: 'SHOE-03',
      name: 'Asics Gel-Nimbus 25 Lite',
      merchant: 'RunnerPoint Hub',
      merchantId: 'MER-RUNPOINT',
      category: 'RUNNING SHOES',
      price: 4699,
      currency: 'INR',
      location: 'National Sports Depot',
      image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80',
      rating: 4.6,
      reviewsCount: 920,
      availability: 'In Stock - 8 Pairs Left',
      delivery: '2-Day Delivery',
      description: 'Maximum-cushion road cruiser featuring PureGEL rearfoot technology and soft FF BLAST PLUS ECO foam.',
      selectionScore: 90,
      selectionProbability: '90%',
      rank: 3,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Midsole Technology': 'PureGEL + FF BLAST PLUS ECO',
        'Weight': '290g Plush Cushion Spec',
        'Heel-to-Toe Drop': '8mm Gentle Transition Drop',
        'Outsole': 'AHARPLUS Rubber High Durability',
        'Upper Material': 'Soft Knit Stretch Collar',
      },
      aiFactors: {
        intentMatch: 91,
        budgetFit: 92,
        productQuality: 92,
        merchantTrust: 93,
        availabilityScore: 88,
        fulfillmentScore: 90,
        catalogCompleteness: 91,
        aiDiscoverability: 90,
        decisionFactors: [
          'Supreme impact shock absorption for recovery runs',
          'Less energetic rebound compared to nitrogen carbon trainers',
          'Limited high-speed tempo capability',
        ],
      },
    },
    {
      id: 'SHOE-04',
      name: 'Puma Deviate Nitro 2',
      merchant: 'TrackMasters Sports',
      merchantId: 'MER-TRACKM',
      category: 'RUNNING SHOES',
      price: 4499,
      currency: 'INR',
      location: 'Bangalore Logistics Hub',
      image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80',
      rating: 4.5,
      reviewsCount: 610,
      availability: 'Available in Sizes 8, 9, 10',
      delivery: '3-Day Delivery',
      description: 'High-responsiveness trainer utilizing NITRO Elite foam and PWRPLATE carbon composite fork.',
      selectionScore: 87,
      selectionProbability: '87%',
      rank: 4,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Midsole Technology': 'NITRO Elite Foam + PWRPLATE Fork',
        'Weight': '260g Responsive Spec',
        'Heel-to-Toe Drop': '6mm Aggressive Drop',
        'Outsole': 'PUMAGRIP All-Surface Compound',
        'Upper Material': 'Breathable Mesh with PWRTAPE',
      },
      aiFactors: {
        intentMatch: 88,
        budgetFit: 93,
        productQuality: 88,
        merchantTrust: 89,
        availabilityScore: 80,
        fulfillmentScore: 86,
        catalogCompleteness: 87,
        aiDiscoverability: 86,
        decisionFactors: [
          'Effective carbon-fork energy transfer on uptempo runs',
          'Narrower toe-box fit noted in 14% of verified buyer feedback',
          'Partial size availability constraint',
        ],
      },
    },
    {
      id: 'SHOE-05',
      name: 'Decathlon Kiprun KD500',
      merchant: 'Decathlon Official',
      merchantId: 'MER-DECA',
      category: 'RUNNING SHOES',
      price: 2999,
      currency: 'INR',
      location: 'National Mega Warehouse',
      image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
      rating: 4.2,
      reviewsCount: 430,
      availability: 'In Stock - 30+ Pairs',
      delivery: 'Next-Day Delivery',
      description: 'Solid entry-level 10k running shoe with Kalensole EVA midsole cushioning and durable road outsole.',
      selectionScore: 81,
      selectionProbability: '81%',
      rank: 5,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Midsole Technology': 'Standard Kalensole EVA Foam',
        'Weight': '280g Standard Spec',
        'Heel-to-Toe Drop': '10mm Traditional Drop',
        'Outsole': 'Abrasion Rubber Grips',
        'Upper Material': 'Standard Synthetic Mesh',
      },
      aiFactors: {
        intentMatch: 75,
        budgetFit: 99,
        productQuality: 78,
        merchantTrust: 96,
        availabilityScore: 98,
        fulfillmentScore: 94,
        catalogCompleteness: 82,
        aiDiscoverability: 80,
        decisionFactors: [
          'Lowest price candidate (₹2,999), proving AI avoids low-spec compromise',
          'Traditional EVA foam lacks energy return of supercritical nitrogen compounds',
          'Absence of composite propulsion plate limits race performance',
        ],
      },
    },
    {
      id: 'SHOE-06',
      name: 'Adidas Solar Glide 6',
      merchant: 'Global Kicks Retail',
      merchantId: 'MER-GKICKS',
      category: 'RUNNING SHOES',
      price: 4750,
      currency: 'INR',
      location: 'Delhi Express Logistics',
      image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&q=80',
      rating: 4.3,
      reviewsCount: 390,
      availability: 'In Stock - 5 Pairs Left',
      delivery: '3-Day Delivery',
      description: 'Durable daily distance running shoe with Boost midsole and Continental tire rubber grip.',
      selectionScore: 78,
      selectionProbability: '78%',
      rank: 6,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Midsole Technology': 'Adidas BOOST Pellet Foam',
        'Weight': '310g Heavy Comfort Spec',
        'Heel-to-Toe Drop': '10mm Stability Drop',
        'Outsole': 'Continental Rubber Grip',
        'Upper Material': 'Circular Knit Recycled Yarn',
      },
      aiFactors: {
        intentMatch: 82,
        budgetFit: 89,
        productQuality: 82,
        merchantTrust: 86,
        availabilityScore: 84,
        fulfillmentScore: 83,
        catalogCompleteness: 84,
        aiDiscoverability: 82,
        decisionFactors: [
          'Heaviest shoe in candidate pool (310g) dampens cadence efficiency',
          'Firm torsion system feels stiff during slow recovery jogs',
          'Scores 6th overall in multi-dimensional GNN selection probability',
        ],
      },
    },
  ],

  PHONE: [
    {
      id: 'PHONE-01',
      name: 'Google Pixel 8a AI Studio Edition',
      merchant: 'MobileWorld Direct',
      merchantId: 'MER-MOBWORLD',
      category: 'PHONE',
      price: 28999,
      currency: 'INR',
      location: 'National Gadget Hub',
      image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80',
      rating: 4.8,
      reviewsCount: 1640,
      availability: 'In Stock (Ships in 24h)',
      delivery: 'Free Next-Day Air Delivery',
      description: 'Cutting-edge Google Tensor G3 processor with on-device Gemini Nano AI, 64MP dual OIS camera with Best Take & Magic Eraser, 120Hz Actua OLED, and 7 years of guaranteed OS updates.',
      selectionScore: 97,
      selectionProbability: '97%',
      rank: 1,
      isYou: true,
      isAiSelected: true,
      attributes: {
        'Processor': 'Google Tensor G3 (Titan M2 Security Coprocessor)',
        'Display': '6.1" Actua OLED 120Hz HDR 2000 nits Peak',
        'Camera System': '64MP OIS Main + 13MP Ultra-Wide Macro',
        'Battery & Charging': '4492mAh + Fast Wireless Qi Charging',
        'Software Support': '7 Full Years OS & Feature Drops (to 2031)',
        'Durability': 'IP67 Water & Dustproof Aluminum Frame',
      },
      aiFactors: {
        intentMatch: 99,
        budgetFit: 96,
        productQuality: 98,
        merchantTrust: 99,
        availabilityScore: 98,
        fulfillmentScore: 99,
        catalogCompleteness: 99,
        aiDiscoverability: 98,
        decisionFactors: [
          '7-year software guarantee provides 2.5x longer lifespan than competitor devices',
          'Benchmark camera performance (136 DXOMARK score leads sub-₹30k tier)',
          'Native hardware support for autonomous agent execution and Gemini Nano',
          'Price ₹28,999 respects ₹30,000 ceiling with ₹1,001 certified buffer',
        ],
      },
    },
    {
      id: 'PHONE-02',
      name: 'Samsung Galaxy A55 5G Metal',
      merchant: 'SamsungDirect Retail',
      merchantId: 'MER-SAMDIR',
      category: 'PHONE',
      price: 29499,
      currency: 'INR',
      location: 'National Electronics Depot',
      image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80',
      rating: 4.6,
      reviewsCount: 1230,
      availability: 'Available - 15 Units',
      delivery: '2-Day Express Delivery',
      description: 'Premium metal frame build with Gorilla Glass Victus+, 5000mAh 2-day battery, Knox Vault security, and 50MP OIS triple camera.',
      selectionScore: 92,
      selectionProbability: '92%',
      rank: 2,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'Exynos 1480 4nm with Xclipse 530 GPU',
        'Display': '6.6" Super AMOLED 120Hz 1000 nits Vision Booster',
        'Camera System': '50MP OIS + 12MP Ultra-Wide + 5MP Macro',
        'Battery & Charging': '5000mAh + 25W Fast Charge',
        'Software Support': '4 Years OS + 5 Years Security Updates',
        'Durability': 'IP67 Metal Frame & Glass Back',
      },
      aiFactors: {
        intentMatch: 94,
        budgetFit: 89,
        productQuality: 93,
        merchantTrust: 97,
        availabilityScore: 94,
        fulfillmentScore: 92,
        catalogCompleteness: 94,
        aiDiscoverability: 93,
        decisionFactors: [
          'Superior metal frame hardware feel and 5000mAh battery life',
          'Exynos 1480 compute performance trails Tensor G3 in neural inference',
          'Price of ₹29,499 leaves tighter ₹501 budget margin',
        ],
      },
    },
    {
      id: 'PHONE-03',
      name: 'OnePlus Nord 4 Snapdragon Pro',
      merchant: 'SmartGear Hub',
      merchantId: 'MER-SMARTGEAR',
      category: 'PHONE',
      price: 27999,
      currency: 'INR',
      location: 'Mumbai Tech Hub',
      image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&q=80',
      rating: 4.5,
      reviewsCount: 870,
      availability: 'In Stock - 8 Units',
      delivery: '2-Day Delivery',
      description: 'Sleek all-metal unibody smartphone powered by Snapdragon 7+ Gen 3 and blisteringly fast 100W SuperVOOC charging.',
      selectionScore: 90,
      selectionProbability: '90%',
      rank: 3,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'Qualcomm Snapdragon 7+ Gen 3 (4nm)',
        'Display': '6.74" 1.5K AMOLED 120Hz 2150 nits',
        'Camera System': '50MP Sony LYT-600 OIS + 8MP Ultra-Wide',
        'Battery & Charging': '5500mAh + 100W Flash Charge (100% in 28m)',
        'Software Support': '4 Years OS Updates',
        'Durability': 'Metal Unibody, IP65 Splashproof',
      },
      aiFactors: {
        intentMatch: 92,
        budgetFit: 94,
        productQuality: 89,
        merchantTrust: 91,
        availabilityScore: 90,
        fulfillmentScore: 89,
        catalogCompleteness: 91,
        aiDiscoverability: 90,
        decisionFactors: [
          'Fastest charging speed in category (100W from 0 to 100% in 28 mins)',
          'Secondary ultra-wide camera sensor is lower resolution (8MP)',
          'IP65 water resistance is lower than IP67 on top two ranked devices',
        ],
      },
    },
    {
      id: 'PHONE-04',
      name: 'Nothing Phone (2a) Plus',
      merchant: 'GizmoPlanet Store',
      merchantId: 'MER-GIZMO',
      category: 'PHONE',
      price: 25999,
      currency: 'INR',
      location: 'Bangalore Hub',
      image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&q=80',
      rating: 4.4,
      reviewsCount: 710,
      availability: 'In Stock - 5 Units',
      delivery: '3-Day Delivery',
      description: 'Iconic transparent Glyph interface with custom MediaTek Dimensity 7350 Pro, dual 50MP cameras, and clean Nothing OS 2.6.',
      selectionScore: 86,
      selectionProbability: '86%',
      rank: 4,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'MediaTek Dimensity 7350 Pro 5G (4nm)',
        'Display': '6.7" Flexible AMOLED 120Hz 1300 nits',
        'Camera System': 'Dual 50MP (Main OIS + 50MP Ultra-Wide)',
        'Battery & Charging': '5000mAh + 50W Fast Charge',
        'Software Support': '3 Years OS + 4 Years Security',
        'Durability': 'IP54 Splash Resistant, Plastic Frame',
      },
      aiFactors: {
        intentMatch: 87,
        budgetFit: 96,
        productQuality: 85,
        merchantTrust: 88,
        availabilityScore: 86,
        fulfillmentScore: 85,
        catalogCompleteness: 88,
        aiDiscoverability: 86,
        decisionFactors: [
          'Distinctive glyph lighting interface and bloatware-free clean OS',
          'Plastic mid-frame build yields lower physical structural rigidity',
          'Basic IP54 splash resistance requires careful handling around liquids',
        ],
      },
    },
    {
      id: 'PHONE-05',
      name: 'Motorola Edge 50 Fusion',
      merchant: 'MobileDeals Express',
      merchantId: 'MER-MDEALS',
      category: 'PHONE',
      price: 22999,
      currency: 'INR',
      location: 'Delhi Distribution Hub',
      image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80',
      rating: 4.3,
      reviewsCount: 520,
      availability: 'In Stock - 25+ Units',
      delivery: 'Next-Day Delivery',
      description: 'Curved 144Hz pOLED display with Snapdragon 7s Gen 2, Sony LYT-700C camera sensor, and IP68 underwater protection.',
      selectionScore: 82,
      selectionProbability: '82%',
      rank: 5,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
        'Display': '6.7" Endless Edge 144Hz pOLED 1600 nits',
        'Camera System': '50MP Sony LYT-700C OIS + 13MP Macro',
        'Battery & Charging': '5000mAh + 68W TurboPower',
        'Software Support': '3 Years OS Updates',
        'Durability': 'IP68 Underwater Submersible',
      },
      aiFactors: {
        intentMatch: 81,
        budgetFit: 99,
        productQuality: 82,
        merchantTrust: 86,
        availabilityScore: 96,
        fulfillmentScore: 89,
        catalogCompleteness: 84,
        aiDiscoverability: 82,
        decisionFactors: [
          'Lowest price candidate (₹22,999) under ₹30k, again illustrating AI quality optimization',
          'Snapdragon 7s Gen 2 benchmark scores 28% lower than Tensor G3 in complex AI tasks',
          'Shorter software support window (3 years) drops long-term value rating',
        ],
      },
    },
    {
      id: 'PHONE-06',
      name: 'Realme 12 Pro+ Periscope Edition',
      merchant: 'GadgetCity Outlets',
      merchantId: 'MER-GCITY',
      category: 'PHONE',
      price: 28499,
      currency: 'INR',
      location: 'Western Retail Warehouse',
      image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&q=80',
      rating: 4.3,
      reviewsCount: 410,
      availability: 'In Stock - 4 Units',
      delivery: '3-Day Delivery',
      description: 'Luxury watch-inspired vegan leather design featuring dedicated 64MP periscope telephoto lens with 3x optical zoom.',
      selectionScore: 79,
      selectionProbability: '79%',
      rank: 6,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Processor': 'Snapdragon 7s Gen 2 (4nm)',
        'Display': '6.7" Curved Vision 120Hz OLED 950 nits',
        'Camera System': '64MP Periscope Zoom + 50MP Sony IMX890 OIS',
        'Battery & Charging': '5000mAh + 67W SuperVOOC',
        'Software Support': '2 Years OS Updates',
        'Durability': 'IP65 Splashproof, Vegan Leather Back',
      },
      aiFactors: {
        intentMatch: 80,
        budgetFit: 91,
        productQuality: 80,
        merchantTrust: 84,
        availabilityScore: 82,
        fulfillmentScore: 81,
        catalogCompleteness: 83,
        aiDiscoverability: 79,
        decisionFactors: [
          'Periscope 3x optical zoom is impressive for photography enthusiasts',
          'Only 2 years of scheduled Android OS updates limits futureproof viability',
          'Pre-installed bloatware packages reduce clean software score',
        ],
      },
    },
  ],

  HEADPHONES: [
    {
      id: 'HEAD-01',
      name: 'Sony WH-1000XM4 ANC Studio Edition',
      merchant: 'AudioPro Official',
      merchantId: 'MER-AUDIOPRO',
      category: 'HEADPHONES',
      price: 9990,
      currency: 'INR',
      location: 'National Audio Depot',
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
      rating: 4.9,
      reviewsCount: 3800,
      availability: 'In Stock - 6 Units Left',
      delivery: 'Free Express Next-Day Delivery',
      description: 'Industry-leading Active Noise Cancelling headphones with QN1 HD Noise Cancelling processor, LDAC Hi-Res wireless audio codec, Speak-to-Chat, and 30-hour battery life.',
      selectionScore: 98,
      selectionProbability: '98%',
      rank: 1,
      isYou: true,
      isAiSelected: true,
      attributes: {
        'Noise Cancellation': 'Dual Sensor HD Noise Cancelling Processor QN1',
        'Battery Life': '30 Hours Playtime (10 min charge = 5 hours)',
        'Audio Codecs': 'LDAC (990kbps Hi-Res), AAC, SBC, DSEE Extreme',
        'Drivers': '40mm Dome Type with Liquid Crystal Polymer (LCP)',
        'Microphones': '5 Precision Beamforming Mics with Voice Pickup',
        'Comfort / Weight': '254g Super-Soft Pressure-Relieving Urethane Foam',
      },
      aiFactors: {
        intentMatch: 99,
        budgetFit: 98,
        productQuality: 99,
        merchantTrust: 99,
        availabilityScore: 97,
        fulfillmentScore: 99,
        catalogCompleteness: 99,
        aiDiscoverability: 99,
        decisionFactors: [
          'Gold-standard ANC processor QN1 ranks #1 across all ambient noise tests',
          'LDAC audiophile support delivers 3x data transmission of regular Bluetooth',
          'Backed by 3,800+ 5-star verified audio engineer and traveler reviews',
          'Official brand-certified partner with direct 1-year replacement warranty',
        ],
      },
    },
    {
      id: 'HEAD-02',
      name: 'Sennheiser Accentum Plus Wireless',
      merchant: 'SonicSound Labs',
      merchantId: 'MER-SONIC',
      category: 'HEADPHONES',
      price: 9490,
      currency: 'INR',
      location: 'Metro Audio Store',
      image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80',
      rating: 4.7,
      reviewsCount: 890,
      availability: 'Available - 8 Units',
      delivery: '2-Day Delivery',
      description: 'Signature Sennheiser acoustic sound with 50-hour marathon battery life, adaptive hybrid ANC, and touch gesture controls.',
      selectionScore: 92,
      selectionProbability: '92%',
      rank: 2,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Noise Cancellation': 'Hybrid Adaptive ANC with Transparency Mode',
        'Battery Life': '50 Hours Marathon Playtime',
        'Audio Codecs': 'aptX Adaptive, AAC, SBC',
        'Drivers': '37mm Dynamic Transducers',
        'Microphones': '2-Mic Beamforming Array',
        'Comfort / Weight': '227g Lightweight Ergonomic Fit',
      },
      aiFactors: {
        intentMatch: 94,
        budgetFit: 95,
        productQuality: 94,
        merchantTrust: 95,
        availabilityScore: 92,
        fulfillmentScore: 91,
        catalogCompleteness: 93,
        aiDiscoverability: 92,
        decisionFactors: [
          'Unrivaled 50-hour battery life outlasts all rivals in the sub-₹10k category',
          'Hybrid ANC trails Sony QN1 processor in high-frequency flight cabin noise',
          'Touchpad controls can be sensitive during accidental head adjustments',
        ],
      },
    },
    {
      id: 'HEAD-03',
      name: 'Bose SoundLink Around-Ear II',
      merchant: 'Premier Audio Store',
      merchantId: 'MER-BOSEDIR',
      category: 'HEADPHONES',
      price: 8999,
      currency: 'INR',
      location: 'National Sound Depot',
      image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80',
      rating: 4.5,
      reviewsCount: 1200,
      availability: 'In Stock - 5 Units Left',
      delivery: '2-Day Delivery',
      description: 'Ultra-comfortable around-ear wireless headphones with TriPort acoustic headphone structure and dual device pairing.',
      selectionScore: 88,
      selectionProbability: '88%',
      rank: 3,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Noise Cancellation': 'Passive Noise Isolation (No Active ANC)',
        'Battery Life': '15 Hours Playtime',
        'Audio Codecs': 'AAC, SBC Standard Bluetooth',
        'Drivers': 'TriPort Acoustic Sound Engine',
        'Microphones': 'Advanced Two-Way Microphone System',
        'Comfort / Weight': '195g Ultra-Featherweight Fit',
      },
      aiFactors: {
        intentMatch: 87,
        budgetFit: 96,
        productQuality: 90,
        merchantTrust: 93,
        availabilityScore: 88,
        fulfillmentScore: 89,
        catalogCompleteness: 89,
        aiDiscoverability: 88,
        decisionFactors: [
          'Supreme featherweight comfort (195g) suitable for all-day continuous wear',
          'Lacks Active Noise Cancellation (ANC), relying solely on passive isolation',
          'Battery life of 15 hours is shorter than contemporary modern standards',
        ],
      },
    },
    {
      id: 'HEAD-04',
      name: 'Audio-Technica ATH-M50xBT2',
      merchant: 'StudioGear Direct',
      merchantId: 'MER-STUDIO',
      category: 'HEADPHONES',
      price: 9800,
      currency: 'INR',
      location: 'Professional Studio Warehouse',
      image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80',
      rating: 4.6,
      reviewsCount: 1450,
      availability: 'In Stock - 10 Units',
      delivery: '3-Day Delivery',
      description: 'Legendary flat studio monitor frequency response with 45mm proprietary drivers, AK4331 DAC, and 50-hour battery life.',
      selectionScore: 85,
      selectionProbability: '85%',
      rank: 4,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Noise Cancellation': 'Passive Studio Isolation Only',
        'Battery Life': '50 Hours Playtime',
        'Audio Codecs': 'LDAC, AAC, SBC (Dedicated DAC)',
        'Drivers': '45mm Large-Aperture Rare Earth Magnet',
        'Microphones': 'Dual Mics with Sidetone Technology',
        'Comfort / Weight': '307g Studio Grade Clamp',
      },
      aiFactors: {
        intentMatch: 86,
        budgetFit: 92,
        productQuality: 93,
        merchantTrust: 90,
        availabilityScore: 90,
        fulfillmentScore: 86,
        catalogCompleteness: 87,
        aiDiscoverability: 85,
        decisionFactors: [
          'Pristine uncolored studio monitor audio loved by music producers',
          'Firm clamping force (307g) causes ear fatigue during casual leisure use',
          'No ANC filtering for commuting or transit environments',
        ],
      },
    },
    {
      id: 'HEAD-05',
      name: 'JBL Live 660NC Bass Edition',
      merchant: 'SoundWave Electronics',
      merchantId: 'MER-SWAVE',
      category: 'HEADPHONES',
      price: 5999,
      currency: 'INR',
      location: 'Central Consumer Depot',
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80',
      rating: 4.2,
      reviewsCount: 680,
      availability: 'In Stock - 30+ Units',
      delivery: 'Next-Day Delivery',
      description: 'Energetic bass-boosted sound with Adaptive Noise Cancelling, Ambient Aware, and 50-hour playtime.',
      selectionScore: 79,
      selectionProbability: '79%',
      rank: 5,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Noise Cancellation': 'Standard Adaptive Noise Cancelling',
        'Battery Life': '50 Hours (40 Hours with ANC on)',
        'Audio Codecs': 'AAC, SBC',
        'Drivers': '40mm Signature Bass Drivers',
        'Microphones': 'Standard Voice Mic',
        'Comfort / Weight': '265g Fabric Headband Fit',
      },
      aiFactors: {
        intentMatch: 78,
        budgetFit: 99,
        productQuality: 78,
        merchantTrust: 88,
        availabilityScore: 98,
        fulfillmentScore: 92,
        catalogCompleteness: 80,
        aiDiscoverability: 79,
        decisionFactors: [
          'Significantly lower price (₹5,999) proves AI balances total utility over cheapness',
          'Plastic build and heavier clamping pressure lower ergonomics rating',
          'Microphone clarity in noisy outdoor environments is noticeably degraded',
        ],
      },
    },
    {
      id: 'HEAD-06',
      name: 'Anker Soundcore Space Q45',
      merchant: 'TechBargains Outlets',
      merchantId: 'MER-TBARG',
      category: 'HEADPHONES',
      price: 7499,
      currency: 'INR',
      location: 'Regional Distribution Center',
      image: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=600&q=80',
      rating: 4.3,
      reviewsCount: 540,
      availability: 'In Stock - 8 Units',
      delivery: '2-Day Delivery',
      description: 'Adaptive active noise cancelling reducing noise by up to 98%, with LDAC Hi-Res Wireless and 65-hour battery life.',
      selectionScore: 76,
      selectionProbability: '76%',
      rank: 6,
      isYou: false,
      isAiSelected: false,
      attributes: {
        'Noise Cancellation': '3-Stage Adaptive Noise Cancelling',
        'Battery Life': '65 Hours (50 Hours with ANC)',
        'Audio Codecs': 'LDAC, AAC, SBC',
        'Drivers': '40mm Double-Layer Silk Diaphragm',
        'Microphones': '2 Mics with AI Call Enhancement',
        'Comfort / Weight': '292g Matte Plastic & Metal',
      },
      aiFactors: {
        intentMatch: 80,
        budgetFit: 95,
        productQuality: 79,
        merchantTrust: 84,
        availabilityScore: 86,
        fulfillmentScore: 84,
        catalogCompleteness: 82,
        aiDiscoverability: 78,
        decisionFactors: [
          'Impressive 65-hour battery life and LDAC wireless codec support',
          'Treble sound profile can sound sharp/sibilant at higher volume levels',
          'Lower overall merchant reliability rating compared to certified partners',
        ],
      },
    },
  ],
};

export const PRESET_CATEGORIES: CategoryPreset[] = [
  {
    id: 'HOTEL',
    name: 'Hotels',
    icon: 'hotel',
    sampleQuery: 'Hotels in Goa under ₹3000',
    category: 'HOTEL',
    budgetCeiling: 3000,
    currency: 'INR',
    candidates: COMMERCE_CATALOG.HOTEL,
  },
  {
    id: 'LAPTOP',
    name: 'Laptops',
    icon: 'laptop',
    sampleQuery: 'Laptops under ₹60000',
    category: 'LAPTOP',
    budgetCeiling: 60000,
    currency: 'INR',
    candidates: COMMERCE_CATALOG.LAPTOP,
  },
  {
    id: 'RUNNING SHOES',
    name: 'Running Shoes',
    icon: 'shoes',
    sampleQuery: 'Running shoes under ₹5000',
    category: 'RUNNING SHOES',
    budgetCeiling: 5000,
    currency: 'INR',
    candidates: COMMERCE_CATALOG['RUNNING SHOES'],
  },
  {
    id: 'PHONE',
    name: 'Smartphones',
    icon: 'phone',
    sampleQuery: 'Smartphones under ₹30000',
    category: 'PHONE',
    budgetCeiling: 30000,
    currency: 'INR',
    candidates: COMMERCE_CATALOG.PHONE,
  },
  {
    id: 'HEADPHONES',
    name: 'Headphones',
    icon: 'headphones',
    sampleQuery: 'Headphones under ₹10000',
    category: 'HEADPHONES',
    budgetCeiling: 10000,
    currency: 'INR',
    candidates: COMMERCE_CATALOG.HEADPHONES,
  },
];
